//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;
 
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]   
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]
    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(11,8)
        [InterceptsLocation(1, "V1rdx21g5a+slUYwHpqULNkAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::Response>)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                var response = castHandler.Invoke();
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<global::Response> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'global::Response' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "V1rdx21g5a+slUYwHpqULKUAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(7,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            builder.Services.AddSingleton<IFeatureProvider, DefaultResponseFeatureProvider<global::Response>>();
            return builder.Build();
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]
    file static class OpenTelemetryLambdaApplicationExtensions
    {
        [InterceptsLocation(1, "V1rdx21g5a+slUYwHpqULLYAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(9,8)
        internal static ILambdaInvocationBuilder UseOpenTelemetryTracingInterceptor(
            this ILambdaInvocationBuilder application
        )
        {
            return application.Use(application.Services.GetOpenTelemetryTracerNoEvent<global::Response>());
        }
    }
}
