//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(11,8)
        [InterceptsLocation(1, "3DxEwWle1IoQD99wxHvHPdkAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action<global::Request>)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = global::Request, Name = request, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetRequiredEvent<global::Request>();
                castHandler.Invoke(arg0);
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "3DxEwWle1IoQD99wxHvHPaUAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(7,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            builder.Services.AddSingleton<IFeatureProvider, DefaultEventFeatureProvider<global::Request>>();
            return builder.Build();
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    
    file static class OpenTelemetryLambdaApplicationExtensions
    {
        [InterceptsLocation(1, "3DxEwWle1IoQD99wxHvHPbYAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(9,8)
        internal static ILambdaInvocationBuilder UseOpenTelemetryTracingInterceptor(
            this ILambdaInvocationBuilder application
        )
        {
            return application.Use(application.Services.GetOpenTelemetryTracerNoResponse<global::Request>());
        }
    }
}
