using Amazon.Lambda.Core;
using Lambda.Host.Interfaces;
using Lambda.Host.Middleware;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

namespace Lambda.Host;

public abstract class LambdaHostedService : IHostedService
{
    protected readonly DelegateHolder DelegateHolder;
    protected readonly ILambdaCancellationTokenSourceFactory LambdaCancellationTokenSourceFactory;
    protected readonly LambdaHostSettings LambdaHostSettings;
    protected readonly IServiceProvider ServiceProvider;
    protected readonly IServiceScopeFactory ServiceScopeFactory;

    protected LambdaHostedService(
        IOptions<LambdaHostSettings> lambdaHostSettings,
        DelegateHolder delegateHolder,
        IServiceProvider serviceProvider,
        ILambdaCancellationTokenSourceFactory lambdaCancellationTokenSourceFactory,
        IServiceScopeFactory serviceScopeFactory
    )
    {
        LambdaHostSettings =
            lambdaHostSettings.Value ?? throw new ArgumentNullException(nameof(lambdaHostSettings));
        DelegateHolder = delegateHolder ?? throw new ArgumentNullException(nameof(delegateHolder));
        ServiceProvider =
            serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        LambdaCancellationTokenSourceFactory =
            lambdaCancellationTokenSourceFactory
            ?? throw new ArgumentNullException(nameof(lambdaCancellationTokenSourceFactory));
        ServiceScopeFactory =
            serviceScopeFactory ?? throw new ArgumentNullException(nameof(serviceScopeFactory));
    }

    public virtual Task StartAsync(CancellationToken cancellationToken) =>
        throw new NotImplementedException(
            "StartAsync has not been generated by the Lambda.Host.SourceGenerators package."
        );

    public virtual Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    protected ILambdaHostContext CreateLambdaHostContext(
        ILambdaContext lambdaContext,
        IServiceScopeFactory serviceScopeFactory,
        CancellationToken cancellationToken
    ) => new LambdaHostContext(lambdaContext, serviceScopeFactory, cancellationToken);

    protected LambdaInvocationDelegate BuildMiddlewarePipeline(LambdaInvocationDelegate handler)
    {
        var pipeline = handler;

        for (var i = DelegateHolder.Middlewares.Count - 1; i >= 0; i--)
        {
            var middleware = DelegateHolder.Middlewares[i];
            pipeline = middleware(pipeline);
        }

        return pipeline;
    }
}
